import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    'zh': {
      'appName': '剧本杀助手',
      'chats': '聊天会话',
      'worldBooks': '世界书',
      'settings': '设置',
      'noCharacters': '暂无角色',
      'tapToCreate': '点击 + 创建一个角色',
      'welcomeTitle': '欢迎来到 Playbook',
      'welcomeSubtitle': '在左侧选择一个角色开始对话，\n或者点击按钮创建一个新角色。',
      'createCharacter': '创建新角色',
      'importCharacter': '导入角色卡',
      'importCharacterSuccess': '角色卡导入成功。',
      'importCharacterFailed': '导入角色卡失败',
      'exportCharacter': '导出角色卡',
      'exportCharacterSuccess': '角色卡导出成功。',
      'exportCharacterFailed': '导出角色卡失败',
      'characterSaveSuccess': '角色保存成功。',
      'searchCharacters': '搜索角色...',
      'deleteCharacter': '删除角色',
      'deleteConfirm': '你确定要删除这个角色吗？与该角色的所有聊天记录都将被永久删除，此操作不可撤销。',
      'cancel': '取消',
      'delete': '删除',
      'edit': '编辑',
      'startChatting': '开始与角色对话吧！',
      'chatSettings': '会话设置',
      'attachImage': '添加图片',
      'typeMessage': '输入消息...',
      'generationFailed': '生成失败',
      'retry': '重试',
      'close': '关闭',
      'error': '错误',
      'offlineWarning': '网络未连接，LLM 功能不可用。',
      'profileDataTitle': '个人资料与数据管理',
      'profileName': '用户昵称',
      'profileNameHint': '用户',
      'clearData': '清空本地数据',
      'clearDataConfirmTitle': '清空所有数据？',
      'clearDataConfirm': '此操作将彻底删除所有角色、会话、消息和设置，且无法恢复。是否确定？',
      'clearDataFailed': '清空数据库失败',
      'exportBackup': '导出备份',
      'importBackup': '导入备份',
      'exportBackupFailed': '导出备份失败',
      'importBackupFailed': '导入备份失败',
      'importConfirmTitle': '导入备份数据？',
      'importConfirm': '导入备份会覆盖当前的所有角色、会话和消息记录。是否确定？',
      'importSuccess': '备份数据导入成功！',
      'exportSuccess': '备份数据导出成功。',
      'clearSuccess': '数据已成功清空。',
      'themeTitle': '界面主题与视觉',
      'themeMode': '主题模式',
      'themeSystem': '系统跟随',
      'themeLight': '浅色模式',
      'themeDark': '深色模式',
      'language': '显示语言',
      'langChinese': '简体中文',
      'langEnglish': 'English',
      'apiConfigTitle': 'LLM API 服务商配置',
      'defaultProvider': '默认 API 服务商',
      'openaiConfig': 'OpenAI 配置',
      'anthropicConfig': 'Anthropic 配置',
      'geminiConfig': 'Gemini 配置',
      'apiKey': 'API Key',
      'baseUrlOptional': 'Base URL（可选）',
      'modelName': '模型名称（Model）',
      'noWorldBooks': '暂无世界书',
      'tapToCreateBook': '点击右上角按钮创建一个新的世界书。',
      'newWorldBook': '新建世界书',
      'addWorldBook': '添加世界书',
      'importWorldBook': '导入世界书',
      'exportWorldBook': '导出世界书',
      'importWorldBookSuccess': '世界书导入成功。',
      'importWorldBookFailed': '导入世界书失败',
      'exportWorldBookSuccess': '世界书导出成功。',
      'exportWorldBookFailed': '导出世界书失败',
      'selectWorldBook': '选择一本世界书来管理其条目设定。',
      'description': '描述信息',
      'add': '添加',
      'entries': '百科条目',
      'addEntry': '添加条目',
      'editEntry': '编辑条目',
      'noEntries': '此世界书中暂无条目',
      'clickToAddEntry': '点击“添加条目”为角色添加背景事实或设定。',
      'requiredName': '名称 *',
      'keywords': '触发关键词',
      'keywordsHint': '例如：苹果, 苹果树 (以逗号分隔)',
      'content': '设定内容',
      'category': '分类',
      'priority': '优先级（值越高越先被匹配）',
      'save': '保存',
      'duplicate': '复制',
      'share': '分享',
      'temperature': '温度 (Temperature)',
      'maxTokens': '最大生成 Token 数',
      'systemPromptOverride': '系统提示词覆盖',
      'loading': '正在加载中...',
      'initialState': '初始状态',
      'fileReadFailed': '无法读取所选文件',
      'greeting': '开场白',
      'exampleMessages': '对话示例',
      'exampleMessagesHint': '<user>: 你好！\n<char>: 很高兴见到你。今天想聊些什么？',
      'systemPrompt': '系统提示词（人物设定）',
      'saveCharacter': '保存角色',
      'newCharacterTitle': '创建角色卡',
      'editCharacterTitle': '编辑角色卡',
      'tapToChangeAvatar': '点击更换头像',
      'characterNameRequired': '角色名称 *',
      'characterNameHint': '例如：阿尔伯特·爱因斯坦',
      'nameRequired': '请输入名称',
      'characterDescriptionRequired': '描述 / 角色人设 *',
      'characterDescriptionHint': '描述角色的性格、背景和特点。',
      'descriptionRequired': '请输入描述',
      'greetingRequired': '开场白 *',
      'greetingHint': '开始新聊天时角色发送的第一句话。',
      'greetingRequiredError': '请输入开场白',
      'systemPromptOverrideHint': '自定义指令，例如：“使用莎士比亚风格说话。”',
      'worldBook': '世界书',
      'selectWorldBookToLink': '选择要关联的世界书',
      'none': '无',
      'addTag': '添加标签',
      'addTagHint': '例如：历史、科幻',
    },
    'en': {
      'appName': 'Playbook',
      'chats': 'Chats',
      'worldBooks': 'World Books',
      'settings': 'Settings',
      'noCharacters': 'No characters yet',
      'tapToCreate': 'Tap + to create one',
      'welcomeTitle': 'Welcome to Playbook',
      'welcomeSubtitle':
          'Select a character from the sidebar to start chatting\nor create a new character to build your own play.',
      'createCharacter': 'Create New Character',
      'importCharacter': 'Import Character',
      'importCharacterSuccess': 'Character imported successfully.',
      'importCharacterFailed': 'Failed to import character',
      'exportCharacter': 'Export Character',
      'exportCharacterSuccess': 'Character exported successfully.',
      'exportCharacterFailed': 'Failed to export character',
      'characterSaveSuccess': 'Character saved successfully.',
      'searchCharacters': 'Search characters...',
      'deleteCharacter': 'Delete Character',
      'deleteConfirm':
          'Are you sure you want to delete this character? All chats with this character will be permanently deleted.',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'startChatting': 'Start chatting with the character!',
      'chatSettings': 'Chat Settings',
      'attachImage': 'Attach Image',
      'typeMessage': 'Type a message...',
      'generationFailed': 'Generation Failed',
      'retry': 'Retry',
      'close': 'Close',
      'error': 'Error',
      'offlineWarning':
          'You are currently offline. LLM services will be unavailable.',
      'profileDataTitle': 'Profile & Data Management',
      'profileName': 'User Profile Name',
      'profileNameHint': 'User',
      'clearData': 'Clear All Local Data',
      'clearDataConfirmTitle': 'Clear all data?',
      'clearDataConfirm':
          'This will delete all characters, chats, messages, and settings. This cannot be undone.',
      'clearDataFailed': 'Failed to clear database',
      'exportBackup': 'Export Backup',
      'importBackup': 'Import Backup',
      'exportBackupFailed': 'Failed to export backup',
      'importBackupFailed': 'Failed to import backup',
      'importConfirmTitle': 'Import Backup?',
      'importConfirm':
          'Importing a backup will overwrite all current characters, chats, messages, and settings. Continue?',
      'importSuccess': 'Backup imported successfully.',
      'exportSuccess': 'Backup exported successfully.',
      'clearSuccess': 'All data cleared successfully.',
      'themeTitle': 'Theme & Visuals',
      'themeMode': 'Theme Mode',
      'themeSystem': 'System Default',
      'themeLight': 'Light Mode',
      'themeDark': 'Dark Mode',
      'language': 'Language',
      'langChinese': '简体中文',
      'langEnglish': 'English',
      'apiConfigTitle': 'LLM API Provider Config',
      'defaultProvider': 'Default API Provider',
      'openaiConfig': 'OpenAI Config',
      'anthropicConfig': 'Anthropic Config',
      'geminiConfig': 'Gemini Config',
      'apiKey': 'API Key',
      'baseUrlOptional': 'Base URL (optional)',
      'modelName': 'Model Name',
      'noWorldBooks': 'No World Books yet',
      'tapToCreateBook': 'Tap the icon above to create one.',
      'newWorldBook': 'New World Book',
      'addWorldBook': 'Add World Book',
      'importWorldBook': 'Import World Book',
      'exportWorldBook': 'Export World Book',
      'importWorldBookSuccess': 'World Book imported successfully.',
      'importWorldBookFailed': 'Failed to import World Book',
      'exportWorldBookSuccess': 'World Book exported successfully.',
      'exportWorldBookFailed': 'Failed to export World Book',
      'selectWorldBook': 'Select a World Book to manage entries.',
      'description': 'Description',
      'add': 'Add',
      'entries': 'Entries',
      'addEntry': 'Add Entry',
      'editEntry': 'Edit Entry',
      'noEntries': 'No entries in this World Book',
      'clickToAddEntry': 'Click Add Entry to document facts.',
      'requiredName': 'Name *',
      'keywords': 'Keywords',
      'keywordsHint': 'e.g. apple, tree (comma separated)',
      'content': 'Content',
      'category': 'Category',
      'priority': 'Priority (higher is evaluated first)',
      'save': 'Save',
      'duplicate': 'Duplicate',
      'share': 'Share',
      'temperature': 'Temperature',
      'maxTokens': 'Max Tokens',
      'systemPromptOverride': 'System Prompt Override',
      'loading': 'Loading...',
      'initialState': 'Initial State',
      'fileReadFailed': 'Cannot read selected file',
      'greeting': 'Greeting',
      'exampleMessages': 'Example Messages',
      'exampleMessagesHint':
          '<user>: Hello!\n<char>: Greetings, my friend! How can I assist you today?',
      'systemPrompt': 'System Prompt',
      'saveCharacter': 'Save Character',
      'newCharacterTitle': 'New Character',
      'editCharacterTitle': 'Edit Character',
      'tapToChangeAvatar': 'Tap to change avatar',
      'characterNameRequired': 'Character Name *',
      'characterNameHint': 'e.g. Albert Einstein',
      'nameRequired': 'Name is required',
      'characterDescriptionRequired': 'Description / Character Persona *',
      'characterDescriptionHint':
          'Describe the personality, background, and quirks of the character.',
      'descriptionRequired': 'Description is required',
      'greetingRequired': 'Greeting Message *',
      'greetingHint':
          'First message the character sends when starting a new chat.',
      'greetingRequiredError': 'Greeting is required',
      'systemPromptOverrideHint':
          'Custom instructions, e.g. "Speak in Shakespearean English."',
      'worldBook': 'World Book',
      'selectWorldBookToLink': 'Select a World Book to link',
      'none': 'None',
      'addTag': 'Add Tag',
      'addTagHint': 'e.g. historical, sci-fi',
    },
  };

  String get(String key) {
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['zh']?[key] ??
        key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['zh', 'en'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
